config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/help', to: 'pages#help'
  get 'pages/testimonials', to: 'pages#testimonials'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 1500 }
  validates :photo, presence: true
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
     @recipes = Recipe.paginate(page: params[:page], per_page: 6)

  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 6)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    # To be changed once chefs are added to the project
    # For now, the recipes will be assigned to the first chef created
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was successfully created!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe wa successfully updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe successfully deleted"
    redirect_to recipes_path
  end

  def like
    like = Like.create(like: params[:like], chef: current_chef, recipe: @recipe)
  if like.valid?
    flash[:success] = "Your selection was succesful"
    redirect_back(fallback_location: root_path)
  else
    flash[:danger] = "You can only like/dislike a recipe once"
    redirect_back(fallback_location: root_path)
  end
end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :photo, ingredient_ids: [])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can only edit or edit your own recipes"
      redirect_to recipes_path
    end
  end

  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_back(fallback_location: root_path)
    end
  end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-8 offset-md-2">
        <%= f.label :name %>
      </div>
      <div class="col-md-8 offset-md-2">
        <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-8 offset-md-2">
        <%= f.label :description %>
      </div>
      <div class="col-md-8 offset-md-2">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps of the recipe" %>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <p>Choose the <strong>main </strong>ingredients</p>
          <hr/>
          <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |check| %>
          <% check.label(class: "input_checkbox label_ingredient") {check.check_box(class: "input_checkbox") + check.text.capitalize} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 offset-md-2">
        <%= f.file_field :photo %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 offset-md-2">
        <%= f.submit class: "btn btn-danger btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="center col-md-8 offset-md-2">
      [<%= link_to "Cancel request and return to recipes", recipes_path %>]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row" id="card-index">
    <div class="col-md-2 chef-info">
    <section class="chef_info center">
      <%= cl_image_tag recipe.photo, height: 100, width: 150, crop: :fill if recipe.photo? %>
    </section>
  </div>
  <div class="col-md-10 well-index no-padding">
    <h3><%= link_to recipe.name.capitalize, recipe_path(recipe) %></h3>
    <p><%= truncate(recipe.description.capitalize, length: 92) %></p>
    <% if recipe.ingredients.any? %>
      <p>Ingredients: <%= render recipe.ingredients %></p>
    <% end %>
    <p>
      <span class="quiet no-padding"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <strong><%= recipe.chef.chefname.capitalize %></strong>
                                          | <%= pluralize(recipe.comments.count, 'Comment') %></small>
    </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="index-btn">
          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-dark btn-sm index-btn" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"}, class: "btn btn-danger btn-sm index-btn" %>
        </div>
      <% end %>
      <div >
  <div class="col-md-10 well-index no-padding index-likes">
    <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
      <i class="fa fa-thumbs-up"></i>
    <% end %> <%= recipe.thumbs_up_total %> |
    <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
      <i class="fa fa-thumbs-down"></i>
    <% end %> <%= recipe.thumbs_down_total %>
  </div>
</div>
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<h1 class= "center col-md-8 offset-md-2">Edit your recipe</h1>
<hr/>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1 align="center">Our recipes</h1>
<hr />
<div class="pagination" style="font-color: black;">
<%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div class="pagination">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<h1 class= "center col-md-8 offset-md-2">Add a new recipe</h1>
<hr/>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1 align="center"><%= @recipe.name.capitalize %></h1>
<hr/>
<div class="col-md-12 show-page no-padding">
  <div class="center recipe-picture-show">
    <%= image_tag(@recipe.photo, height: 350, width: 400, crop: :fill, alt: "Recipe's picture") %>
  </div>
  <h4 class="show-description col-md-12 no-padding"><strong>Description: </strong></h4>
  <%= simple_format(@recipe.description.capitalize) %>
  <% if @recipe.ingredients.any? %>
  <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="center col-md-3 offset-9 no-padding">
    <p class="right">Created <%= time_ago_in_words(@recipe.created_at) %> ago by <strong><%= @recipe.chef.chefname.upcase %></strong>
    </p>
    <p class="chef-photo"><%= link_to cl_image_tag(@recipe.chef.photo_chef, height: 150, width: 200, crop: :fill, alt: "Chef profile's picture"), chef_path(@recipe.chef)%></p>
  </div>
  <div class="col-md-10 text-left no-padding recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-dark btn-lg" %>
    <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"}, class: "btn btn-danger btn-lg" %>
    <% end %>
    <%= link_to "Return to recipes", recipes_path, class: "btn btn-dark btn-lg" %>
  </div>
</div>
<hr></hr>
<div class="row liking">
  <div class="col-md-12 likes-section">
    <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
    <i class="fa fa-thumbs-up"></i>
    <% end %> <%= @recipe.thumbs_up_total %> | <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
    <i class="fa fa-thumbs-down"></i>
    <% end %> <%= @recipe.thumbs_down_total %>
  </div>
</div>

</br>
<% if logged_in? %>
<div class="form-group">
  <div class="col-md-12 no-padding">
    <h3>Want to leave a comment?</h3>
    <div class="col-md-12 no-padding"><%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %></div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12 no-padding">
    <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Enter your comment here" %>
  </div>
</div>
<div>
  <div class="col-md-12 no-padding">
    <%= f.submit "Submit comment", class: "btn btn-danger btn-lg" %>
  </div>
</div>
<% end %>
<% end %>

  </br>
  <% if @recipe.comments != 0 %>
  <div class="row" >
    <div class="col-md-12">
      <h3 >Previous Comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  <% else %>
  <div class="row" >
    <div class="col-md-12">
    <h3>No Comments Yet!</h3>
  </div>
    </div>
  <% end %>
  </div>