config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/help', to: 'pages#help'
  get 'pages/testimonials', to: 'pages#testimonials'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_admin, except: [:show, :index]

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 6)
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 6)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully created"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient name was successfully updated"
      redirect_to @ingredient
    else
      reder 'edit'
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to ingredients_path
    end
  end

end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>


<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-8 offset-md-2">
        <%= f.label :name %>
      </div>
      <div class="col-md-8 offset-md-2">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter ingredient", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-8 offset-md-2">
        <%= f.submit(@ingredient.new_record? ? " Add ingredient" : "Update ingredient", class: "btn btn-danger btn-lg") %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="center col-md-8 offset-md-2">
    [<%= link_to "Cancel request and return to recipes", recipes_path %>]
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge badge-light text-center"><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/edit.html.erb
<h1 class= "center col-md-8 offset-md-2">Edit ingredient name</h1>
<hr/>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<h1 class= "center col-md-8 offset-md-2">Available ingredients</h1>
<hr/>

<div class="center col-md-4 offset-4">
  <%= will_paginate %>
  <% @ingredients.each do |ingredient| %>
    <ul class="listing">
      <div class="card">
        <div >
          <li class="chef-title"><p><%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %></p></li>
          <li><small><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes %></small></li>
          <% if logged_in? && current_chef.admin? %>
            <li><%= link_to "Edit this ingredient", edit_ingredient_path(ingredient) %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<h1 class= "center col-md-8 offset-md-2">Add a new ingredient</h1>
<hr/>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<h1 class= "center col-md-8 offset-md-2"><%= @ingredient.name.upcase %></h1>
<hr/>

<% if @ingredient.recipes.count != 0 %>
  <div class="col-md-4 offset-4 center">
    <h4>Recipe's containing <%= @ingredient.name %></h4>
  </div>
  <%= will_paginate @ingredient_recipes %>
  <%= render 'recipes/recipe', obj: @ingredient_recipes %>
  <%= will_paginate @ingredient_recipes %>
<% else %>
  <h4 align="center">No recipes yet</h4>
<% end %>