config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/help', to: 'pages#help'
  get 'pages/testimonials', to: 'pages#testimonials'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

end

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!-- Footer -->
  <section id="footer">
    <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left">
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><h4>Karen Hoyos</h4></li>
            <li class="list-inline-item"><a href="https://www.linkedin.com/in/karen-hoyos/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
            <li class="list-inline-item"><a href="https://github.com/Kahoza" target="_blank"><i class="fa fa-github"></i></a></li>
            <li class="list-inline-item"><a href="https://codepen.io/WildKoala/" target="_blank" target="_blank"><i class="fa fa-codepen"></i></a></li>
          </ul>
        </div>
        </hr>
      </div>
    </div>
  </section>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class=" col-md-10 offset-1">
    <% flash.each do |name, message| %>
    <div class="alert alert-<%= name %>">
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= message %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg " style="background-color: #FFFFFF;">
  <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="dropdown">
      <ul>
      <ul class="nav-item dropdown navbar"></ul>
       <a class="nav-link dropdown-toggle a-navbar" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ingredients</a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <ul>
          <%= link_to "Ingredients", ingredients_path, class: 'dropdown-item btn-css-class', style: 'color:black' %>
        </ul>
          <% Ingredient.all.each do |ingredient| %>
            <ul class="navbar-text"><%= link_to ingredient.name.capitalize, ingredient_path(ingredient), class:'dropdown-item btn-css-class', style: 'color:black' %></ul>
          <% end %>
          <% if logged_in? && current_chef.admin? %>
            <div class="dropdown-divider"></div>
              <ul><%= link_to  "New ingredient",  new_ingredient_path, class: 'dropdown-item btn-css-class', style: 'color:black'  %></ul>
          <% end %>
      </div>
      </ul>
    </div>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link a-navbar" href="/chefs">Chefs <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link a-navbar" href="/recipes">Recipes <span class="sr-only">(current)</span></a>
      </li>
    </ul>


    <div class="dropdown">
    <ul>
      <ul class="nav-item dropdown navbar-right"></ul>
      <% if logged_in? %>
      <a class="nav-link dropdown-toggle a-navbar" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.upcase %>'s profile <small><%= "Admin" if current_chef.admin? %></small></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <ul>
          <%= link_to "My profile", chef_path(current_chef), class: 'navbar-text btn-css-class', style: 'color:black' %>
        </ul>
        <ul>
          <%= link_to "Edit my profile", edit_chef_path(current_chef), class: 'navbar-text btn-css-class', style: 'color:black' %>
        </ul>
        <ul>
          <%= link_to "Add a new recipe", new_recipe_path, class: 'navbar-text btn-css-class', style: 'color:black' %>
        </ul>
        <div class="dropdown-divider"></div>
          <ul><%= link_to  "Log out", logout_path, method: :delete, class: 'navbar-text btn-css-class', style: 'color:black'  %></ul>
          <% else %>
          <a class="nav-link a-navbar navbar-text" href="/login">Login <span class="sr-only"></span></a>
        <% end %>
      </div>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'public/packs/png' %>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' unless @no_footer %>
  </body>
</html>